## ------------------Redshift-------------------
redshift = 34.6535344537155

## ------------------Cosmology------------------
ombh2 = 0.02242
omch2 = 0.11933
tau = 0.053
As = 2.08e-9
ns = 0.9655
H0 = 67.66
alpha_s = 0.0

## ---------------Frequency channel-------------
bandwidth_frac = 0.3 ## unit: MHz; 
                     ## effective bandwidth 
                     ## (e.g. at central frequency 40 MHz, this gives a bandwidth of 12 MHz)
channel_width = 10 ## unit: kHz

## ---------------Interferometer----------------
L = 100000 ## unit: m
           ## separation between the center of two circular arrays
D_min = 4.5 ## unit: m
           ## minimum baseline length
D_max = 15000 ## unit: m
              ## maximum baseline length
N_antenna = 100000.0 ## number of antennas
D0 = -2100 ## unit: m
w = 6200 ## unit: m
         ## baseline distribution parameters

## --------------Survey Parameters-------------
t_tot = 100000 ## unit: hours
              ## total observation time

dlnk_perp = 0.05 ## unit: Mpc^-1
                  ## width of k-bin in transverse direction (in log scale)
dk_para = 0.2 ## unit: Mpc^-1
               ## width of k-bin in line-of-sight direction

##----------------Antenna---------------------
N_pol = 2 ## number of polarizations
freq_ref = 50 ## unit: MHz
              ## reference frequency in the model of system temperature T_sys
S_area = 20000 ## unit: deg^2
               ## survey area
FoV = 10300 ## unit: deg^2
            ## antenna's field of view 
gain = 2 ## antenna's gain







