## ------------------Redshift-------------------
redshift = 34.65

## ------------------Cosmology------------------
ombh2 = 0.02242 ## baryon density 
omch2 = 0.11933 ## cold dark matter density 
tau = 0.053 ## reionization optical depth
As = 2.08e-9 ## amplitude of primordial power spectrum
ns = 0.9655 ## spectral index
H0 = 67.66 ## Hubble constant; unit: km/s/Mpc
alpha_s = 0.0 ## running of the spectral index

## ---------------Frequency channel-------------
bandwidth_frac = 0.3 ## unit: MHz; 
                     ## effective bandwidth 
                     ## (e.g. at central frequency 40 MHz, this gives a bandwidth of 12 MHz)
channel_width = 10 ## unit: kHz

## ---------------Interferometer Configuration----------------
n_stations = 4 ## number of stations/circular arrays in the interferometer

D_min = 4.5 ## unit: m
            ## minimum baseline length
D_max = 5100 ## unit: m
             ## maximum baseline length
N_antenna = 300000.0 ## number of antennas
                      ## for a double-array, this is the number of antennas in each circular array

## only modify when having a DOUBLE or TRIPLE arrays
L = 100000 ## unit: m
           ## separation between the center of two circular arrays

## only modify when using FarView/FarSide configuration
D0 = -20000 ## unit: m
w = 10000 ## unit: m
         ## baseline distribution parameters for FarView/FarSide

## --------------Survey Parameters-------------
t_tot = 100000 ## unit: hours
              ## total observation time

dlnk_perp = 0.05 ## unit: Mpc^-1
                  ## width of k-bin in transverse direction (in log scale)
dk_para = 0.2 ## unit: Mpc^-1
               ## width of k-bin in line-of-sight direction

##----------------Antenna---------------------
N_pol = 2 ## number of polarizations
freq_ref = 50 ## unit: MHz
              ## reference frequency in the model of system temperature T_sys
S_area = 20000 ## unit: deg^2
               ## survey area
FoV = 10300 ## unit: deg^2
            ## antenna's field of view 
gain = 2 ## antenna's gain







